
- name: Add user
  shell: echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('{{jenkins_new_user}}', '{{jenkins_new_user_pass}}')" | {{jenkins_cli_cmd}} groovy = --username {{jenkins_user}} --password {{jenkins_password}}
