---
- name: Import jenkins key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins
  yum: name=jenkins-{{jenkins_version}}-1.1 state=latest
  register: jenkins_install

- debug: var=jenkins_install

- include: start_jenkins.yml

- name: Unlock Jenkins
  shell: echo {{jenkins_version}} > /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion

- include: start_jenkins.yml
