---
- include: start_jenkins.yml

- name: List plugins
  shell: "{{ jenkins_cli_cmd }} list-plugins --username {{jenkins_user}} --password {{jenkins_password}} | cut -f 1 -d ' '"
  when: plugins is defined
  register: plugins_installed

- name: Install/update plugins
  shell: "{{ jenkins_cli_cmd }} install-plugin --username {{jenkins_user}} --password {{jenkins_password}} {{ item }}"
  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1
  with_items: "{{ plugins }}"

- include: start_jenkins.yml

- name: List plugins to be updated
  shell: "{{ jenkins_cli_cmd }} -noKeyAuth list-plugins --username {{jenkins_user}} --password {{jenkins_password}} | grep ')$' | cut -f 1 -d ' ' | awk 1 ORS=' '"
  register: plugins_updates

- debug: var=plugins_updates

- name: Update plugins
  shell: "{{ jenkins_cli_cmd }} install-plugin --username {{jenkins_user}} --password {{jenkins_password}} {{ item }}"
  with_items: plugins_updates.stdout.split(" ")
  when:
    - plugins_updates.stdout != ''
    - item == ''

- include: start_jenkins.yml
