---
jenkins_version: '2.70'
java_version: 1.8.0
plugins:
  - git
  - timestamper
  - rebuild
  - jobConfigHistory
  - copyartifact
  - workflow-aggregator
  - build-pipeline-plugin
  - build-monitor-plugin
  - ansicolor
  - ws-cleanup
jenkins_connection_delay: 30
jenkins_connection_retries: 3
